Updated database schema to include all data required for website. Moved cartset view out of main digiplay.sql to digiplay-views.sql Removed default data from Dia files into digiplay-data.sql
git-svn-id: https://www.radio.warwick.ac.uk/repos/dps/trunk@191 156110d5-7a05-0410-a37f-c1950ce4f093

diff --git a/db/dpsinstall b/db/dpsinstall
--- a/db/dpsinstall
+++ b/db/dpsinstall
@@ -156,9 +156,14 @@ if [[ ! -f digiplay-triggers.sql ]]; then
 	printf "Installation Aborted.\n"
 	exit -1
 fi
+if [[ ! -f digiplay-data.sql ]]; then
+	printf " -> Missing database default data!\n"
+	printf "Installation Aborted.\n"
+	exit -1
+fi
 
 printf " -> Creating objects..."
-$PSQL -qf digiplay.sql $DBNAME #2>/dev/null
+$PSQL -qf digiplay.sql $DBNAME 2>/dev/null
 if [[ $? > 0 ]]; then
 	printf " -> Failed to generate database objects\n"
 	printf "Installation Aborted. Empty database remains.\n"
@@ -172,10 +177,19 @@ if [[ $? > 0 ]]; then
 	printf "Installation Aborted. Mess remains.\n"
 	exit -1
 fi
+printf "done.\n"
 printf " -> Creating triggers..."
 $PSQL -qf digiplay-triggers.sql $DBNAME 2>/dev/null
 if [[ $? > 0 ]]; then
 	printf " -> Failed to generate database triggers\n"
+	printf "Installation Aborted. Mess remains.\n"
+	exit -1
+fi
+printf "done.\n"
+printf " -> Inserting default data..."
+$PSQL -qf digiplay-data.sql $DBNAME 2>/dev/null
+if [[ $? > 0 ]]; then
+	printf " -> Failed to insert default data\n"
 	printf "Installation Aborted. Mess remains.\n"
 	exit -1
 fi
