Added extra checks to DB install script Separated conversion from the Visio generated IBM DB2 schema (digiplay.db2) Added conversion script (db2tosql) Removed generated digiplay.sql file (this is generated on install) Added DB_PORT configuration option to digiplay.conf Added quick installation guide Added Makefile.settings to set compile options Updated Makefile.in to support conditional Authentication modules Added conditional compile to studio_manage code for different Auth methods Added PSql authentication using cleartext passwords Improved and optimised config class (added case-insensitivity) Improved some string handling functions in dps.cpp
git-svn-id: https://www.radio.warwick.ac.uk/repos/dps/trunk@141 156110d5-7a05-0410-a37f-c1950ce4f093

diff --git a/db/dpsinstall b/db/dpsinstall
--- a/db/dpsinstall
+++ b/db/dpsinstall
@@ -1,91 +1,171 @@
 #!/bin/bash
-
 printf "\n"
 printf "Radio Warwick Digital Playout System\n"
 printf "Database Installation script\n"
 printf "Copyright (c) 2006 Radio Warwick\n\n"
 
-# check for configuration and use defaults if necessary
+# check we can access the pwd. This problem will usually because the user
+# has su'ed from root to a user without access to the pwd which then causes
+# errors further on.
+DIR=`pwd`
+cd $DIR > /dev/null 2>&1
+if [[ $? > 0 ]]; then
+	printf "Cannot cd to `pwd`, does this user have permission?\n"
+	printf "Installation Aborted.\n"
+	exit -1
+fi
+
+# check for some basic linux commands are available. fail if we're missing
+# these very basic commands!
+if [[ ! (`which sed` && `which grep` && `which cut`) ]]; then
+	printf "Missing basic unix tools. Cannot continue.\n"
+	exit -1;
+fi
+
+# check we have PostgreSQL client somewhere in the path.
+if [[ ! `which psql` ]]; then
+	printf "Cannot find PostgreSQL client (psql) in path.\n"
+	exit -1;
+fi
+
+# define psql command
+PSQL=`which psql`
+
+# check version of psql client and warn if less than major=8
+PSQL_MAJOR=`psql --version | grep psql | cut -f 3 -d ' ' | cut -f 1 -d '.'`
+if [[ $PSQL_MAJOR < 8 ]]; then
+	printf "WARNING: PostgreSQL client is less than 8.0.\n"
+	printf "It is recommended to use PostgreSQL v8.0 or later.\n"
+fi
+
+# check if the default configuration file exists, and if not warn user
 if [ ! -f /etc/digiplay.conf ]; then
-    printf "No digiplay configuration file found, please create one.\n";
-    printf "Will assume database name of \'digiplay\'.\n";
-    printf "Do you wish to abort installation? (Y/n) ";
+    printf "No digiplay configuration file found, please create one.\n"
+    printf "Will assume database name of \'digiplay\'.\n"
+    printf "Do you wish to abort installation? (Y/n) "
     read cont;
     if [ "${cont:-Y}" == "Y" ] || [ "$cont" == "y" ]; then
-        printf "Database installation aborted.\n";
+        printf "Database installation aborted.\n"
         exit 0;
     fi
-    DBNAME=digiplay;
-    DBUSER=digiplay_user;
+	# default values
+    DBNAME=digiplay
+	DBHOST="127.0.0.1"
+	DBPORT="5432"
+    DBUSER=digiplay_user
 else
-    DBNAME=`cat /etc/digiplay.conf | grep DB_NAME | cut -d "=" -f 2`;
-    DBUSER=`cat /etc/digiplay.conf | grep DB_USER | cut -d "=" -f 2`;
+	printf "Parsed /etc/digiplay.conf\n"
+	# parse the following values from the configuration file
+    DBNAME=`cat /etc/digiplay.conf | grep DB_NAME | cut -d "=" -f 2`
+	DBHOST=`cat /etc/digiplay.conf | grep DB_HOST | cut -d "=" -f 2`
+	DBPORT=`cat /etc/digiplay.conf | grep DB_PORT | cut -d "=" -f 2`
+    DBUSER=`cat /etc/digiplay.conf | grep DB_USER | cut -d "=" -f 2`
 fi
-printf "Database: $DBNAME \n";
-printf "Username: $DBUSER \n";
+# display the values which will be used
+printf "Database: $DBNAME\n"
+printf "Host:     $DBHOST\n"
+printf "Port:     $DBPORT\n"
+printf "Username: $DBUSER \n\n"
 
-# create database
+# compile the psql command with host and port specification if necessary
+if [[ $DBHOST != "127.0.0.1" ]]; then 
+	PSQL="$PSQL -h $DBHOST"
+fi
+if [[ $DBPORT != "5432" ]]; then 
+	PSQL="$PSQL -p $DBPORT"
+fi
+
+# check the current user has access to access the database server
+$PSQL -ls > /dev/null 2>&1
+if [[ $? > 0 ]]; then
+	printf "User '$USER' does not have database access.\n"
+	printf " -> su to the 'postgres' user, or create a role for this user\n";
+	printf "Installation Aborted.\n"
+	exit -1;
+fi
+
+# try to create database
 printf "Checking for existing database...";
-if [ `psql -ls | grep " $DBNAME " | wc -l` == "1" ]; then
+if [ `$PSQL -ls | grep " $DBNAME " | wc -l` == "1" ]; then
 	printf "\n"
 	printf " -> Found existing database '$DBNAME'\n";
 	printf "\nDo you want to backup existing database? [Y/n]: ";
 	read backup;
 	if [ "${backup:-Y}" == "Y" ] || [ "$backup" == "y" ]; then
 		printf " -> Backing up current sustainer playlist..."
-		psql -tc "SELECT md5 FROM audio WHERE sustainer='t'" $DBNAME | cut -d ' ' -f 2 > sustainer.bak
+		$PSQL -tc "SELECT md5 FROM audio WHERE sustainer='t'" $DBNAME \
+				| cut -d ' ' -f 2 > sustainer.bak
 		printf "done\n"
 		printf " -> Current sustainer playlist saved to 'sustainer.bak'\n"
 		printf " -> Backing up existing database..."
-		if [ `psql -ls | grep ${DBNAME}_bak | wc -l` == "1"]; then
-			psql -qc "DROP DATABASE ${DBNAME}_bak;" template1
+		if [ `$PSQL -ls | grep ${DBNAME}_bak | wc -l` == "1"]; then
+			$PSQL -qc "DROP DATABASE ${DBNAME}_bak;" template1
 		fi
-		psql -qc "ALTER DATABASE digiplay RENAME TO ${DBNAME}_bak;" template1
+		$PSQL -qc "ALTER DATABASE digiplay RENAME TO ${DBNAME}_bak;" template1
 		printf "done.\n"
 		printf " -> Existing database saved as ${DBNAME}_bak\n"
 	else
-		printf "\nInstallation was terminated by the user.\n"
-		exit -1
+		printf " -> Removing existing database..."
+		$PSQL -qc "DROP DATABASE ${DBNAME};" template1
+		printf "done.\n"
 	fi
 else
 	printf "none found.\n"
 fi
 
+# create the database and check if we were successful
 printf "Creating ${DBNAME} database..."
-psql -qc "CREATE DATABASE ${DBNAME};" template1
+$PSQL -qc "CREATE DATABASE ${DBNAME};" template1
+if [[ $? > 0 ]]; then
+	printf "Unable to create database ${DBNAME}.\n"
+	printf " -> Does this user have permission to create databases?\n"
+	printf "Installation Aborted.\n"
+	exit -1;
+fi
 printf "done.\n"
 
-# create users
+# create user for digiplay software as specified in config file, if it doesn't
+# already exist
 printf "Creating digiplay database users..."
-if [ ! `psql -tqc "select usename from pg_user where usename='$DBUSER';" template1` ]; then
-	psql -qc "CREATE USER $DBUSER;" template1
+if [ ! `$PSQL -tqc "select usename from pg_user where usename='$DBUSER';" template1` ]; then
+	$PSQL -qc "CREATE USER $DBUSER;" template1
 fi
 printf "done.\n"
 
 # create all the relations, views, etc
-printf "Processing DDL script..."
-echo "BEGIN TRANSACTION;" > /tmp/digiplay.sql.new
-sed -e 's/VARCHAR(10)/VARCHAR/g' -e 's/"id" INTEGER not null/"id" SERIAL/g' \
-   digiplay.sql >> /tmp/digiplay.sql.new
-echo "END TRANSACTION;" >> /tmp/digiplay.sql.new
-printf "done.\n"
-printf "Generating database objects..."
-psql -qf /tmp/digiplay.sql.new $DBNAME  2>/dev/null
-rm /tmp/digiplay.sql.new
+printf "Now generating database objects...\n"
+if [[ ! -f digiplay.sql ]]; then
+	if [[ ! -f digiplay.db2 ]]; then
+		printf " -> No database schema available!\n"
+		printf "Installation Aborted.\n"
+		exit -1
+	fi
+	printf " -> Processing DDL script..."
+	./db2tosql digiplay.db2 > digiplay.sql
+	printf "done.\n"
+fi
+
+printf " -> Creating objects..."
+$PSQL -qf digiplay.sql $DBNAME 2>/dev/null
+if [[ $? > 0 ]]; then
+	printf " -> Failed to generate database objects\n"
+	printf "Installation Aborted.\n"
+	exit -1
+fi
 printf "done.\n"
 
 # grant permissions to the digiplay_user on everything (for now)
 printf "Granting database permissions..."
 SQL="SELECT relname FROM pg_class WHERE (relkind = 'r' OR relkind = 'S')
 AND relname !~ '^pg_' AND relname !~ '^sql_' ORDER BY relname"
-OBJ=`psql -t -c "${SQL}" $DBNAME`
+OBJ=`$PSQL -t -c "${SQL}" $DBNAME`
 OBJ=`echo ${OBJ} | sed 's/ /, /g'`
 SQL="GRANT ALL ON ${OBJ} TO $DBUSER"
-psql -qc "${SQL}" $DBNAME
+$PSQL -qc "${SQL}" $DBNAME
 printf "done.\n"
 
 # import default data
 printf "Importing data..."
-psql -qf data.sql $DBNAME
+$PSQL -qf data.sql $DBNAME
 printf "done.\n\n";
 printf "Installation Complete.\n\n";
